version: "2"
services:
  nginx:
    build: .
    container_name: nginx
    external_links:
      - baobah-front-end-app
      - baobah_api
    ports:
      - 80:80
      - 443:443
    networks:
      - baobah_network

networks:
  baobah_network:
    external: true
